name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        makeLatest: true
        draft: true
    - name: Use WordPress Release Post Action
      uses: mastashake08/wordpress-release-post-action@main
      with:
        wordpress_url: ${{ secrets.WORDPRESS_URL }}
        wordpress_username: ${{ secrets.WORDPRESS_USERNAME }}
        wordpress_app_password: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        wordpress_category_id: ${{ secrets.WORDPRESS_APP_CATEGORY_ID }}
